### ISSUE TITLE
Completion not working

### ISSUE THREAD

**Issue by top2014** [oblitum/YouCompleteMe#11]
Hello,

I wanted to try this version of YCM, as it gives function paremter hints, which to me is a very cool feature.

I was able to build it using clang 3.7. 

However, the completion engine simply does not work. It does not perform the basic completions as the original YCM does. It does not prompt parameter hints, either.

Please advise! Any thoughts will be appreciated! Thanks!

**Comment by oblitum** [comment]
I can't help you if the only information you give is that it doesn't work for you. You should try `:YcmDiags` as a first step. Please see [CONTRIBUTING.md](https://github.com/oblitum/YouCompleteMe/blob/master/CONTRIBUTING.md).

**Comment by top2014** [comment]
@oblitum Thanks for prompt response. Let me follow the instructions to provide more detail.

My system is a brand new Ubuntu 14.04.2, x64. VIM version is at the end. I'm using Vundle to manage plugins. Originally, I was able to get the original YCM working on my system. It works well.

To try your fork, I removed the original YCM folder from VIM bundle. Then I used the script below to install your version. The build looks successful. Then I started a simple C++ code to try. Unfortunately, it does not show completions as I type. It does not prompt parameter hints. Note that the same code and test settings work for the original YCM. 

More information can be found below. Please help!

# The scripts I used to install your version.

#!/bin/bash
if [ ! -d ~/.vim/bundle/YouCompleteMe ]; then
    cd ~/.vim/bundle/ 
    git clone https://github.com/oblitum/YouCompleteMe.git 
    cd YouCompleteMe
    git submodule update --init --recursive
fi

if [ ! -d ~/Downloads/cling-Ubuntu-14.04-64bit-dec5717d4c ]; then
    cd ~/Downloads
    wget https://ecsft.cern.ch/dist/ec/dist/cling/current/cling-Ubuntu-14.04-64bit-dec5717d4c.tar.bz2
    tar -xjf cling-Ubuntu-14.04-64bit-dec5717d4c.tar.bz2
    cd cling-Ubuntu-14.04-64bit-dec5717d4c
    sudo cp -R -f * /usr/local/
fi

mkdir ~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm
cd ~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm
CC=~/Downloads/cling-Ubuntu-14.04-64bit-dec5717d4c/bin/clang CXX=~/Downloads/cling-Ubuntu-14.04-64bit-dec5717d4c/bin/clang++ CPATH=~/Downloads/cling-Ubuntu-14.04-64bit-dec5717d4c/lib/clang/3.7.0/include cmake -G "Unix Makefiles" -DUSE_CLANG_COMPLETER=ON -DPATH_TO_LLVM_ROOT=~/Downloads/cling-Ubuntu-14.04-64bit-dec5717d4c -DEXTERNAL_LIBCLANG_PATH=~/Downloads/cling-Ubuntu-14.04-64bit-dec5717d4c/lib/libclang.so ~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp
make ycm_support_libs
make ycm_core



# Here is relevant .vimrc info:
Plugin 'oblitum/YouCompleteMe'
let g:ycm_global_ycm_extra_conf='~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
let g:ycm_server_keep_logfiles = 1
let g:ycm_server_log_level = 'debug'


# Here is the YCMDebugInfo:
-- Server has Clang support compiled in: True
-- Clang version: clang version 3.7.0 (....)
-- Flags for XX.cpp loaded from ..../.ycm_extra_conf.py
....

# Here is the YCM server stderr log info:

2015-08-23 19:14:28,541 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
2015-08-23 19:14:28,988 - INFO - Received event notification
2015-08-23 19:14:28,988 - DEBUG - Event name: BufferVisit
2015-08-23 19:14:28,991 - INFO - Received event notification
2015-08-23 19:14:28,991 - DEBUG - Event name: FileReadyToParse
2015-08-23 19:14:28,991 - INFO - Adding buffer identifiers for file: /tmp/main.cpp
2015-08-23 19:14:30,007 - INFO - Received health request
2015-08-23 19:14:30,011 - INFO - Received filetype completion available request
2015-08-23 19:14:33,110 - INFO - Received debug info request
2015-08-23 19:14:47,350 - INFO - Received event notification
2015-08-23 19:14:47,350 - DEBUG - Event name: FileReadyToParse
2015-08-23 19:14:47,350 - INFO - Adding buffer identifiers for file: /tmp/main.cpp
2015-08-23 19:14:47,360 - INFO - Received event notification
2015-08-23 19:14:47,360 - DEBUG - Event name: InsertLeave
2015-08-23 19:14:49,293 - INFO - Received debug info request
2015-08-23 19:15:10,860 - INFO - Received event notification
2015-08-23 19:15:10,860 - DEBUG - Event name: FileReadyToParse
2015-08-23 19:15:10,860 - INFO - Adding buffer identifiers for file: /tmp/main.cpp
2015-08-23 19:15:11,633 - INFO - Received event notification
2015-08-23 19:15:11,633 - DEBUG - Event name: FileReadyToParse
2015-08-23 19:15:11,633 - INFO - Adding buffer identifiers for file: /tmp/main.cpp
2015-08-23 19:15:13,576 - INFO - Received event notification
2015-08-23 19:15:13,576 - DEBUG - Event name: FileReadyToParse
2015-08-23 19:15:13,577 - INFO - Adding buffer identifiers for file: /tmp/main.cpp
2015-08-23 19:15:13,579 - INFO - Received event notification
2015-08-23 19:15:13,580 - DEBUG - Event name: InsertLeave
2015-08-23 19:15:15,572 - INFO - Received event notification
2015-08-23 19:15:15,572 - DEBUG - Event name: FileReadyToParse
2015-08-23 19:15:15,572 - INFO - Adding buffer identifiers for file: /tmp/main.cpp
2015-08-23 19:15:15,574 - INFO - Received event notification
2015-08-23 19:15:15,574 - DEBUG - Event name: InsertLeave
2015-08-23 19:15:15,574 - INFO - Adding ONE buffer identifier for file: /tmp/main.cpp



# VIM version : 
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:59)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     +tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    +xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/harfbuzz     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/include/tcl8.6  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_LARGEFILE64_SOURCE=1  
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib

**Comment by oblitum** [comment]
Do you have a `.ycm_extra_conf` properly setup?

**Comment by oblitum** [comment]
YcmDebugInfo is truncated.

**Comment by oblitum** [comment]
Also. I can't assure Cling is a safe route for sure since it's a Clang fork with a specific purpose. I don't use it myself as a Clang replacement.

**Comment by top2014** [comment]
I just put the default .ycm_extra_conf in the same folder as the cpp file without modifying anything: https://github.com/oblitum/ycmd/blob/master/cpp/ycm/.ycm_extra_conf.py

The complete YcmDebugInfo is as this picture
![ycmdebuginfo](https://cloud.githubusercontent.com/assets/8945114/9446896/1ca05712-4a49-11e5-8482-3eadf40959ab.PNG)

**Comment by top2014** [comment]
I found that if I press <C-Space>, it will show completion suggestions as YCM normally does. And when I did this, I found in the YCM server log there appeared the following logs which indicated completion request received:

2015-08-24 10:22:43,494 - INFO - Received event notification
2015-08-24 10:22:43,494 - DEBUG - Event name: FileReadyToParse
2015-08-24 10:22:43,494 - INFO - Adding buffer identifiers for file: /tmp/main.cpp
2015-08-24 10:22:47,297 - INFO - Received completion request
2015-08-24 10:22:47,297 - DEBUG - Using filetype completion: True

If I don't press <C-Space> but just keep typing, it simply does not show any completion prompts. The server log does not show any "completion request" log anymore, either. 

Is it because the  key-typing triggering event for "completion request" is somehow altered or disabled?

In addition, no matter what I do, the function argument hints never show up...

**Comment by oblitum** [comment]
To add more information, please show a sample code you expect completion and it doesn't happen as well as `:YcmDiags` output.

**Comment by top2014** [comment]
Here is the complete code
``` cpp
#include <cstdio> 
class MyClass 
{ 
    public: 
        void printMsg(void);     
        void printMsg(int a, int b);     
        void fu1(char a, int b);
    private: 
        ; 
};
void MyClass::printMsg (void) 
{ 
    printf("From Class\n");
}
void MyClass::printMsg (int a, int b) 
{ 
    printf("%d\t%d\n", a, b);
}
void MyClass::fu1(char a, int b)
{
    printf("%c\t%d\n", a, b);
}
int g_num = 128; 
static void printMsg (int i) 
{ 
    printf("%d\n", i);
} 
static void printMsg () 
{ 
    printf("From Method\n");
} 
int foo(int a, int b, int c)
{
    printf("%d\t%d\t%d\n", a, b, c);
    return 1;
}
void bar(int a, int b)
{
    printf("%c\t%d\n", a, b);
}
int main (void) 
{ 
    MyClass one; 
    one.printMsg(1, 2);
    one.printMsg();
    bar(foo(1, 2, 3), 42);
    printMsg(10);
    printMsg();

    return  0; 
} 
```
Here is the :YcmDiags output
```
/usr/include/stdio.h|33 col 11 error| 'stddef.h' file not found
```

**Comment by oblitum** [comment]
You have compilation errors in your file, you should fix them first:

- Make sure you have build tools installed for your platform, like on Ubuntu, the build-essential package.
- Take care of the flags you really want in .ycm_extra_conf.
- I always check what default include directories for a given set of flags I get, for example:
  - `echo | clang -std=c++11 -stdlib=libc++ -v -E -x c++ -`  
  (check [YCM issue 303](https://github.com/Valloric/YouCompleteMe/issues/303))
- I put those headers as `-isystem` headers in my `.ycm_extra_conf` that uses the same flags I've passed to the previous command.

**Comment by top2014** [comment]
After setting flags in .ycm_extra_conf as you suggested, :YcmDiags outputs no errors now for the same code. And the code does compile.

Here is the modified part of .ycm_extra_conf
```
'-isystem',
'/usr/include',
'-isystem',
'/usr/local/include',
'-isystem',
'/usr/local/bin/../lib/clang/3.7.0/include',
'-isystem',
'/usr/include/x86_64-linux-gnu',
```
However, YCM remains not working.

I want to bring this into emphasize. **If I type ctrl+space, the completion suggestion does show up as expected**, as the original YCM will do. But **if only typing without ctrl+space, completion simply does not show up**. Furthermore, the desired feature of **function argument hints never show up**.

Thank you.

**Comment by oblitum** [comment]
No ideas anymore. I use this on Ubuntu, Arch and OS X. Other users also use it and never complained about this behavior. I'm concluding there's an issue with your system, it may be anything, vim version, cling (not clang) version.

I'm closing it but you may feel free to provide more information if you start digging the problem further.

**Comment by top2014** [comment]
Thanks @oblitum . I will try this again after clang-3.7 comes out.
