### ISSUE TITLE
Better param-completion

### ISSUE THREAD

**Issue by agauniyal** [oblitum/YouCompleteMe#14]
Why not providing in place dummy parameters for editing rather than showing parameters as hints? For example : emacs irony-mode does this as follows

![2015-11-26-005027_1366x768_scrot](https://cloud.githubusercontent.com/assets/7630575/11407207/5c4cb0c2-93d7-11e5-8b70-dd981664b32e.png)

and then edit and jump onto next parameter with <tab>. Better UX, better hints.

**Comment by agauniyal** [comment]
Irony-mode is open source too, if you'd want to take a look [here](https://github.com/Sarcasm/irony-mode).

**Comment by oblitum** [comment]
This has been discussed at https://github.com/Valloric/YouCompleteMe/issues/234 and https://github.com/Valloric/YouCompleteMe/issues/1300.

The original implementation was through dummy params and deprecated, I've weighted and evolved to the current behavior, not going back.

**Comment by agauniyal** [comment]
You had a gif displaying your previous fork that was doing the same thing as above. Was that a different branch? Or do you have any sources of that, so I could have it for my use case?

**Comment by agauniyal** [comment]
![This_one](https://camo.githubusercontent.com/a823bf9ec55b5b31aaf5a28946f7a0a80f7fc560/687474703a2f2f692e696d6775722e636f6d2f6d7873713959792e676966)

**Comment by oblitum** [comment]
It is this branch https://github.com/oblitum/YouCompleteMe/tree/clang_complete-params, but it's very old and dead. It's not updated to use completion information that I've added to clang, nor it's up-to-date with YCM master.
