### ISSUE TITLE
Function parameter hinting results in an error

### ISSUE THREAD

**Issue by bstaletic** [oblitum/YouCompleteMe#15]
# Issue Prelude

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood YCM's [CONTRIBUTING][cont] document.
- [x] I have read and understood YCM's [CODE_OF_CONDUCT][code] document.
- [x] I have read and understood YCM's [README][readme], **especially the
  [Frequently Asked Questions][faq] section.**
- [x] I have searched YCM's issue tracker to find issues similar to the one I'm
  about to report and couldn't find an answer to my problem. ([Example Google
  search.][search])
- [x] If filing a bug report, I have included the output of `vim --version`.
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 15 2016 10:11:05)
Included patches: 1-5
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl/dyn
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
-clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl/dyn        +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lncurses -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee-lm
```
- [x] If filing a bug report, I have included the output of `:YcmDebugInfo`.
```
Printing YouCompleteMe debug information...
-- Server has Clang support compiled in: True
-- Clang version: clang version 3.8.1 (tags/RELEASE_381/final)
-- C-family completer debug information:
--   Configuration file found and loaded
--   Configuration path: /home/bstaletic/Temp/.ycm_extra_conf.py
--   Flags: ['-Wall', '-Wextra', '-fexceptions', '-DNDEBUG', '-DUSE_CLANG_COMPLETER', '-std=c89', '-x', 'c', '-isystem', '/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/include', '-isystem', '/usr/local/include', '-isystem', '/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1', '-isystem', '/usr/include', '-resource-dir=/home/bstaletic/.vim/pack/ycm/opt/YouCompleteMe/third_party/ycmd/ycmd/../clang_includes', '-fspell-checking']
-- Server running at: http://127.0.0.1:47801
-- Server process ID: 8676-- Server logfiles:
--   /tmp/ycm_temp/server_47801_stdout.log
--   /tmp/ycm_temp/server_47801_stderr.log
```
- [x] If filing a bug report, I have included the output of
  `:YcmToggleLogs stderr`.
```
2016-09-16 13:55:57,822 - INFO - Received event notification
2016-09-16 13:58:03,025 - INFO - Received debug info request
2016-09-16 14:02:26,888 - INFO - Received health request
2016-09-16 14:12:26,998 - INFO - Received health request
2016-09-16 14:13:48,328 - INFO - Received debug info request
2016-09-16 14:13:56,851 - INFO - Received debug info request
```
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
Arch linux x86_64
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
```c
#include <stdio.h>

int main() {
         scanf(|);
         return 0;
}
```
With the file above, where cursor position is denoted by |, vim reports an error. It is not a problem with just scanf, or just the first parameter. Every function behaves the same as well as any parameter of a function. Here's the error:
```
Error detected while processing function youcompleteme#Complete[25]..SNR>46_GetCompletions[1]..<SNR>46_Pyeval:
line    2:
E859: Failed to convert returned python object to vim value
```
- [x] **I understand this is an open-source project staffed by volunteers and
  that any help I receive is a selfless, heartfelt _gift_ of their free time. I
  know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

Thank you for adhering to this process! It ensures your issue is resolved
quickly and that neither your nor our time is needlessly wasted.

# Issue Details

I have tried compiling ycm_core in different ways, including using boost both as provided by Arch linux and as provided by YouCompleteMe and using both python2 and python3. None of that had any effect on the error message. In july I had a Gentoo installation and this ycm fork worked perfectly fine, but that laptop has not been updated since and I can't check the latest commit on it as I don't have it at hand. My best guess is that this change in behaviour is caused by a recent commit upstream that has been merged here. The other laptop that 

[If filing a bug report, please include **a list of steps** that describe how to
reproduce the bug you are experiencing. Also include test code if relevant.]

[cont]: https://github.com/Valloric/YouCompleteMe/blob/master/CONTRIBUTING.md
[code]: https://github.com/Valloric/YouCompleteMe/blob/master/CODE_OF_CONDUCT.md
[readme]: https://github.com/Valloric/YouCompleteMe/blob/master/README.md
[faq]: https://github.com/Valloric/YouCompleteMe/blob/master/README.md#faq
[search]: https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fgithub.com%2FValloric%2FYouCompleteMe%2Fissues%20python%20mac

**Comment by bstaletic** [comment]
Now, I'm really confused. I have just tried resetting to commit 57ddc2 but it is still producing the same error even though I'm sure that commit was before I tied this fork on the Gentoo laptop.

**Comment by oblitum** [comment]
I'm on updated ArchLinux and I've compiled the same vim version in your report to try your test code. I have no issues and couldn't reproduce your problem.

These are my compilation flags:

```python
flags = [
'-x', 'c',
'-Wall',
'-Wextra',
'-pedantic',
'-isystem', '/usr/local/include',
'-isystem', '/usr/lib/clang/3.8.1/include',
'-isystem', '/usr/include',
]
```
I didn't try yours because the looked a bit strange for me.

**Comment by bstaletic** [comment]
I've just tried removing every other plugin and commenting out everything in vimrc except "filetype plugin indent on" and "syntax on". Still the error remains. Are you using testing repos of Arch? Could that be a problem?

That said, since this now looks like a problem on my laptop should I close this, since the bug tracker is not made for individual support?

**Comment by oblitum** [comment]
You may close since there's a strong suspicion it's a problem in your setup, you may reopen it in case it's a plugin issue. Answering your question, I'm not using "testing repos of Arch", I'm dunno what they are, so I have no idea.

**Comment by bstaletic** [comment]
I was thinking of [testing] and [community-testing], I'll check that in a minute. I'll close either way, since that could only be an issue on my end.

**Comment by oblitum** [comment]
Ah, I'm not using them.

**Comment by bstaletic** [comment]
I have disabled [testing] and [community-testing], but that too did not help. Fiddling with configuration lead me to the conclusion that it is something on my end. I'll play with it tomorrow. Thanks anyway.
