### ISSUE TITLE
Functions with more than one parameter.

### ISSUE THREAD

**Issue by melonaerial** [oblitum/YouCompleteMe#17]
Hello!
I've tried your fork for function parameters hints. It works good. Thank you very much for your job, but I think it is better to make it work like in classic IDE, when your see not only next parameter, but all function parameters and current parameter highlighted(like shown here https://www.jetbrains.com/clion/features/img/1.2/smart-editor/parameter_info.png ).  Or maybe show function signature somewhere like have been shown here https://github.com/Valloric/YouCompleteMe/issues/2304#issuecomment-244571724 . I think it can be rather useful.

**Comment by oblitum** [comment]
Thanks. This has been implemented formally at `https://github.com/oblitum/YouCompleteMe/tree/clang_complete-params`. I have abandoned that first implementation.

Sorry but this is a wonfix for me as it's an experimental fork implemented as I'd enjoy. Both hints and prototypes have been kept short in popup to avoid cluttering the interface and not be much invasive.

If you're interested in the full signatures, you should try let `set completeopt+=preview`. It's available from upstream as well as from this fork, but this fork tweaks it to point the current argument as well.

**Comment by oblitum** [comment]
Did you check preview window implementation from this fork, what you think about it regarding your request?

**Comment by oblitum** [comment]
For example, this is what happens when you cycle hints:

![screenshot from 2016-10-24 00-33-05](https://cloud.githubusercontent.com/assets/1269815/19632058/8f83fee0-9981-11e6-8d60-9c2628c2660a.png)

**Comment by melonaerial** [comment]
@oblitum Yeah, I know about preview window, but I just don't like how its look. I think better is to make it look like in classic IDE, because I don't like this preview window in bottom of the screen and I have to on top of the screen.

**Comment by oblitum** [comment]
@melonaerial OK. Sorry, I guess your request goes against this specific tweak for example https://github.com/oblitum/ycmd/commit/614f8284e62e925d2166120471892edceaf1d238. Please take a look at the referred issue. I try to provide a less cluttered interface for both hints as for normal completion and leave the rest for the preview, which by the way I also don't like much.
