### ISSUE TITLE
GoTo subcommands jumping to function definition instead of function parameter declaration 

### ISSUE THREAD

**Issue by bstaletic** [oblitum/YouCompleteMe#18]
# Issue Prelude

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood YCM's [CONTRIBUTING][cont] document.
- [x] I have read and understood YCM's [CODE_OF_CONDUCT][code] document.
- [x] I have read and understood YCM's [README][readme], **especially the
  [Frequently Asked Questions][faq] section.**
- [x] I have searched YCM's issue tracker to find issues similar to the one I'm
  about to report and couldn't find an answer to my problem. ([Example Google
  search.][search])
- [x] If filing a bug report, I have included the output of `vim --version`.
- [x] If filing a bug report, I have included the output of `:YcmDebugInfo`.
- [x] If filing a bug report, I have included the output of
  `:YcmToggleLogs stderr`.
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by volunteers and
  that any help I receive is a selfless, heartfelt _gift_ of their free time. I
  know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps.**

Thank you for adhering to this process! It ensures your issue is resolved
quickly and that neither your nor our time is needlessly wasted.

# Issue Details
Hello,

I've stumbled onto a strange behavior that is a result of changes made by this fork. The upstream is not having the same problem. Here's an example that causes this behavior:
```c
#include <libopencm3/stm32/gpio.h>

void main(void)
{
        gpio_set(GPIOA, GPIO1);
}
```
No matter where the cursor is on that line it will jump to:
```c
void gpio_set(uint32_t gpioport, uint16_t gpios);
```
Or the appropriate function definition. If a cursor is on a parameter I would expect it to jump to that parameter's declaration. And, as I mentioned, it works like one would expect with the upstream branch. The code I have posted is from (libopencm3 library)[https://github.com/libopencm3/libopencm3]. In the next few days I'll try to replicate it with a much more minimal example. For now I'm trying to use YouCompleteMe for (my project)[https://github.com/bstaletic/eurobot2k17]. Currently I'm working around this issue buy having up-to-data tags and using <C-]>. Also, I've tried replicating this issue with a "hello world" like program, but with such a simple example I've been unable to replicate the issue. So if the cursor was on `GPIOA` it should jump to:
```c
#define GPIOA GPIO_PA
```
And if it was on `GPIO1` it should jump to:
```c
#define GPIO1				(1 << 1)
```
Once again this all works properly with the upstream branch.
### My .ycm_extra_conf.py
```python
def FlagsForFile( filename, **kwargs ):
    return { 'flags': [
    '-x',
    'c',
    '-DSTM32F4',
    '-DSTM32F407VG',
    '-DSTM32F4CCM',
    '-Wall',
    '-Wextra',
    '-Wno-main',
    '-std=c99',
    '-I',
    'libopencm3/include/',
    '-isystem',
    '/usr/lib/gcc/arm-none-eabi/6.2.0/include',
    '-isystem',
    '/usr/lib/gcc/arm-none-eabi/6.2.0/include-fixed',
    '-isystem',
    '/usr/arm-none-eabi/include',
    '-I.'
] }
```
### Vim version
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 17 2016 08:58:28)
Included patches: 1-86
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl             +cmdline_compl   +digraphs        +folding         +langmap         -mouseshape      -mzscheme        +python3/dyn     +syntax          -toolbar         +writebackup
+arabic          +cmdline_hist    -dnd             -footer          +libcall         +mouse_dec       +netbeans_intg   +quickfix        +tag_binary      +user_commands   +X11
+autocmd         +cmdline_info    -ebcdic          +fork()          +linebreak       +mouse_gpm       +num64           +reltime         +tag_old_static  +vertsplit       +xfontset
-balloon_eval    +comments        +emacs_tags      +gettext         +lispindent      -mouse_jsbterm   +packages        +rightleft       -tag_any_white   +virtualedit     -xim
-browse          +conceal         +eval            -hangul_input    +listcmds        +mouse_netterm   +path_extra      +ruby/dyn        +tcl/dyn         +visual          -xpm
++builtin_terms  +cryptv          +ex_extra        +iconv           +localmap        +mouse_sgr       +perl/dyn        +scrollbind      +termguicolors   +visualextra     +xsmp_interact
+byte_offset     +cscope          +extra_search    +insert_expand   +lua/dyn         -mouse_sysmouse  +persistent_undo +signs           +terminfo        +viminfo         +xterm_clipboard
+channel         +cursorbind      +farsi           +job             +menu            +mouse_urxvt     +postscript      +smartindent     +termresponse    +vreplace        -xterm_save
+cindent         +cursorshape     +file_in_path    +jumplist        +mksession       +mouse_xterm     +printer         +startuptime     +textobjects     +wildignore
+clientserver    +dialog_con      +find_in_path    +keymap          +modify_fname    +multi_byte      +profile         +statusline      +timers          +wildmenu
+clipboard       +diff            +float           +lambda          +mouse           +multi_lang      +python/dyn      -sun_workshop    +title           +windows
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -march=native -O3 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2  -march=native -O3 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_F
ORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-neede
d,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_pe
rl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -
ltclstub8.6 -ldl -lz -lpthread -lieee -lm
```
### YcmDebugInfo
```
Printing YouCompleteMe debug information...
-- Server has Clang support compiled in: True
-- Clang version: clang version 3.9.0 (tags/RELEASE_390/final)
-- C-family completer debug information:
--   Configuration file found and loaded
--   Configuration path: /home/bstaletic/eurobot2k17/.ycm_extra_conf.py
--   Flags: ['-x', 'c', '-DSTM32F4', '-DSTM32F407VG', '-DSTM32F4CCM', '-Wall', '-Wextra', '-Wno-main', '-std=c99', '-I', 'libopencm3/include/', '-isystem', '/usr/lib/gcc/arm-none-eabi/6.2.0/i
nclude', '-isystem', '/usr/lib/gcc/arm-none-eabi/6.2.0/include-fixed', '-isystem', '/usr/arm-none-eabi/include', '-I.', '-resource-dir=/home/bstaletic/.vim/pack/bundle/opt/YouCompleteMe/third
_party/ycmd/ycmd/../clang_includes', '-fspell-checking']
-- Server running at: http://127.0.0.1:39339
-- Server process ID: 2444
-- Server logfiles:
--   /tmp/ycmd_39339_stdout_I9lINN.log
--   /tmp/ycmd_39339_stderr_9noKry.log
```
### YcmToggleLogs stderr
```
2016symotion-prefix)zz-11-27 20:01:54,984 - INFO - Received event notification
2016-11-27 20:01:55,003 - INFO - Received event notification
2016-11-27 20:01:55,004 - INFO - Adding buffer identifiers for file: /home/bstaletic/eurobot2k17/initialisation/gpio_config.c
2016-11-27 20:01:56,653 - INFO - Received health request
2016-11-27 20:01:56,661 - INFO - Received event notification
2016-11-27 20:01:56,663 - INFO - Received filetype completion available request
2016-11-27 20:01:56,674 - INFO - Received event notification
2016-11-27 20:01:56,674 - INFO - Adding buffer identifiers for file: /home/bstaletic/eurobot2k17/drivers/actuators/motion/motion.c
2016-11-27 20:01:56,700 - INFO - Received event notification
2016-11-27 20:01:56,732 - INFO - Received event notification
2016-11-27 20:01:56,787 - INFO - Received event notification
2016-11-27 20:01:56,789 - INFO - Received event notification
2016-11-27 20:01:56,789 - INFO - Adding buffer identifiers for file: /home/bstaletic/eurobot2k17/drivers/actuators/motion/motion.c
```
### OS information
Archlinux completely updated as of 27.11.2016

[If filing a bug report, please include **a list of steps** that describe how to
reproduce the bug you are experiencing. Also include test code if relevant.]

[cont]: https://github.com/Valloric/YouCompleteMe/blob/master/CONTRIBUTING.md
[code]: https://github.com/Valloric/YouCompleteMe/blob/master/CODE_OF_CONDUCT.md
[readme]: https://github.com/Valloric/YouCompleteMe/blob/master/README.md
[faq]: https://github.com/Valloric/YouCompleteMe/blob/master/README.md#faq
[search]: https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fgithub.com%2FValloric%2FYouCompleteMe%2Fissues%20python%20mac

**Comment by bstaletic** [comment]
I've done some further testing and have found the following:
- This fork's GoTo always makes a correct jump if cursor is not placed on a parameter
- This fork's GoTo always makes a correct jump if cursor is placed on the first parameter
- This fork's GoTo sometimes jumps to function declaration if cursor is placed on second, or later parameter of a function.

I'm going to experiment a bit more to find out what exactly does sometimes mean.

**Comment by oblitum** [comment]
OK, thanks, I'd like to try this also, but I'd prefer a reduced case to try.

**Comment by bstaletic** [comment]
I will reopen this as I've closed it by mistake. Sorry about that.

I've managed to make a 13 line file demonstrating the issue and it seems related to whitespace agnostic changes.

Here's the file that works:
```c
#define A 2
#define B 5

int add(int a, int b)
{
        return a+b;
}

int main(void)
{
	add(A,B);
	return 0;
}
```
Only the B identifier is of interest, others work properly. Though if add() took three parameters it would cause the same problems. I'll use the '|' character to denote cursor position.

In the file, as it is above, if the cursor is on B and `:YcmCompleter GoTO` is invoked it will correctly jump to:
```c
#define B| 5
```
But if I change the line 11 to
```c
        add(A, B);
```
And again have cursor on B, then invoke `:YcmCompleter GoTo`, it will jump to a different location, namely line number 4 instead of 6:
```c
int a|dd(int a, int b)
```

**Comment by bstaletic** [comment]
Correction: Even the jump to the first parameter of a function can be wrong if preceded by a whitespace. So if the line is changed to:
```c
        add( A, B );
```
then jump to either A or B is wrong. The whitespace after B doesn't actually matter, it's there just because it does make the line look ugly.

**Comment by bstaletic** [comment]
Here's an even shorter version of the program having this issue:
```c
#include <stdio.h>

int main(void)
{
	int a;
	printf("%d\n", a);
	return 0;
}
```
Again, YCM doesn't correctly jump if cursor is on `a`.

**Comment by oblitum** [comment]
I'm gonna take a look at this, thanks for the report, I was able to reproduce it as well.

**Comment by oblitum** [comment]
I've noticed the following which may help you while it's not fixed.

When the cursor is not at the first identifier's character, it jumps correctly, like the following:

```c++
#include <stdio.h>

int main(void)
{
	int ab = 0;
	printf("%d\n", ab);
	return 0;
}
```

If you put the cursor over 'b' in `ab`, GoTo works as expected. If you put it over 'a', it behaves like reported.

**Comment by bstaletic** [comment]
Great, thanks for that. To be honest, it didn't even occur to me to try jumping from the second or any other character that's not the first. I guess I'll be training myself to jump to the end of the identifier for now. Thanks for looking into this.

Also, what I have tried just now is this:
```c
#include <stdio.h>

int main(void)
{
	int ab = 0;
	printf("%d\n",           

                                         ab);
	return 0;
}
```
The white space is deliberately made this big. If the cursor is anywhere on the whitespace and `:YcmCompleter GoTo` is invoked it jumps to the function definition. That seems to me like a reasonable thing to do. On the other hand, it makes me think this is an off-by-one issue where whatever is iterating over whitespace catches the first character of the identifier as well. To tell the truth I have not dived into the code though, this is just base on experimentation.

**Comment by oblitum** [comment]
That's what I think is happening too (I also didn't dig the code about this yet).

**Comment by bstaletic** [comment]
Not wanting to post a bunch more comments here, I've made a fork where I've made the change that apparently solves the problem, but it's a terrible hack. There's a leghty comment in the file changed.

**Comment by oblitum** [comment]
@bstaletic please remove your patch and try this fix, it's the correct solution.

**Comment by oblitum** [comment]
Thanks for the report by the way.

**Comment by bstaletic** [comment]
@oblitum 
Works perfectly in my project now! Thanks for your effort!
