### ISSUE TITLE
Place holder doesn't highlight parameters correctly

### ISSUE THREAD

**Issue by ofenerci** [oblitum/YouCompleteMe#6]
Dear Oblitum,

I have a problem about the placeholder. When I use TAB to browse through paremeter placeholders, the TAB doesn't exactly place itself onto the parameters. For example, let's take MPI_SendRecv function: 

MPI_Sendrecv_replace(⟪void *buf⟫, ⟪int count⟫, ⟪MPI_Datatype datatype⟫, ⟪int dest⟫, ⟪int sendtag⟫, ⟪int source⟫, ⟪int recvtag⟫, ⟪MPI_Comm comm⟫, ⟪MPI_Status *status⟫)

After I modify the first parameter inside the function, I enter TAB to jump onto the second place holder. But the second parameter is highlighted partially such as  that some part of words "MPI_Datatype data" is highlighted but a few letters are not highlighted "type". I wonder it is possible something due to my .vimrc file. I am using Debian Testing with vim 7.4 

Best Regards,
Ozhan

**Comment by oblitum** [comment]
I'll close this issue since I won't be supporting this particular branch anymore. There's a new method being used which is being provided in the master branch. It aims to be merged in the original repository at some point in time.
